# Generated by Django 2.0.4 on 2018-05-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('cid', 'name')},
        ),
    ]
