# Generated by Django 2.0.4 on 2018-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('rid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Resource',
            },
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
