# Generated by Django 2.0.4 on 2018-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180515_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemailid',
            field=models.CharField(db_column='EEmailid', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pass_field',
            field=models.CharField(db_column='pass', max_length=50),
        ),
    ]
