# Generated by Django 2.0.4 on 2018-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
