# Generated by Django 2.0.4 on 2018-05-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0006_auto_20180522_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
