# Generated by Django 2.0.4 on 2018-05-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0007_delete_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eemailid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='efname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='elname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pass_field',
        ),
    ]
