# Generated by Django 2.0.4 on 2018-05-23 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0008_auto_20180523_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='eid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
