# Generated by Django 2.0.4 on 2018-05-23 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_customers', '0011_auto_20180523_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateField()),
                ('cexpiry', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Registration')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField()),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='eid',
            field=models.ForeignKey(blank=True, db_column='eid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mid',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Membership'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Resource'),
        ),
    ]
