# Generated by Django 2.0.4 on 2018-05-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0021_auto_20180523_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cexpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mid',
            field=models.ForeignKey(blank=True, db_column='mid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Membership'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rid',
            field=models.ForeignKey(blank=True, db_column='rid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Resource'),
        ),
    ]
