# Generated by Django 2.0.4 on 2018-05-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0023_auto_20180525_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cexpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='eid',
            field=models.ForeignKey(blank=True, db_column='eid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mid',
            field=models.ForeignKey(blank=True, db_column='mid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_customers.Membership'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
