# Generated by Django 2.0.4 on 2018-05-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0025_auto_20180525_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rid',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
