# Generated by Django 2.0.4 on 2018-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0027_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
