# Generated by Django 2.0.4 on 2018-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_customers', '0029_employee_toid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='etherstopay',
            field=models.FloatField(default=0.0),
        ),
    ]
